CREATE DATABASE MONARCA;

CREATE TABLE SILLAR(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    PESO INT,
    COLOR VARCHAR(250),
    IMG TEXT
);
CREATE TABLE OVALINES(
    LARGO INT,
    ANCHO INT,
    NOMBRE VARCHAR(250),
    IMG TEXT
);
CREATE TABLE TABIQUE_APARENTE(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    PESO FLOAT,
    IMG TEXT,
    NOMBRE VARCHAR(256)
);
CREATE TABLE MURO_LLORON(
    ALTO INT,
    ANCHO INT,
    IMG TEXT
);
CREATE TABLE FUENTES(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    IMG TEXT,
    NOMBRE VARCHAR(256)
);
CREATE TABLE ADHESIVOS(
    DESCRIPCION TEXT,
    PESO INT,
    RENDIMIENTO TEXT
    NOMBRE VARCHAR(256),
    IMG TEXT,
);
CREATE TABLE CANTERA(
    LARGO INT,
    ANCHO INT,
    GROSOR INT
    NOMBRE VARCHAR(256),
    IMG TEXT,
);
CREATE TABLE FACHALETA(
    MEDIDAS TEXT,
    COLOR VARCHAR(256),
    IMG TEXT,
);
CREATE TABLE PIEDRA_BOLA_MARMOL(
    COLOR VARCHAR(256),
    IMG TEXT,
    MEDIDAS TEXT
);
CREATE TABLE PIEDRA_LAJA_IRREGULAR(
    COLOR VARCHAR(256),
    IMG TEXT,
    
);
CREATE TABLE CELOSÍAS(
    MODELO VARCHAR(256),
    LARGO INT,
    ANCHO INT,
    ALTO INT,
    PESO FLOAT,
    PIEZAS INT,
    IMG TEXT
);
CREATE TABLE TEJAS(
    COLOR VARCHAR(256),
    LARGO FLOAT,
    ALTO FLOAT,
    ACABADOS VARCHAR(256),
    ESPESOR FLOAT,
    USO VARCHAR(256),
    PESO FLOAT,
    IMG TEXT
);
CREATE TABLE PIEZAS_ESPECIALES(
    NOMBRE VARCHAR(256),
    IMG TEXT
);

CREATE TABLE MURO_LLORON(
    ALTO INT,
    ANCHO INT,
    IMG TEXT
);
CREATE TABLE FUENTES(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    IMG TEXT,
    NOMBRE VARCHAR(256)
);
CREATE TABLE ADHESIVOS(
    DESCRIPCION TEXT,
    PESO INT,
    RENDIMIENTO TEXT,
    NOMBRE VARCHAR(256),
    IMG TEXT
);
CREATE TABLE CANTERA(
    LARGO INT,
    ANCHO INT,
    GROSOR INT,
    NOMBRE VARCHAR(256),
    IMG TEXT
);
CREATE TABLE FACHALETA(
    MEDIDAS TEXT,
    COLOR VARCHAR(256),
    IMG TEXT
);
CREATE TABLE PIEDRA_BOLA_MARMOL(
    COLOR VARCHAR(256),
    IMG TEXT,
    MEDIDAS TEXT
);
CREATE TABLE PIEDRA_LAJA_IRREGULAR(
    COLOR VARCHAR(256),
    IMG TEXT
    
);
CREATE TABLE CELOSÍAS(
    MODELO VARCHAR(256),
    LARGO INT,
    ANCHO INT,
    ALTO INT,
    PESO FLOAT,
    PIEZAS INT,
    IMG TEXT
);
CREATE TABLE TEJAS(
    COLOR VARCHAR(256),
    LARGO FLOAT,
    ALTO FLOAT,
    ACABADOS VARCHAR(256),
    ESPESOR FLOAT,
    USO VARCHAR(256),
    PESO FLOAT,
    IMG TEXT
);
CREATE TABLE PIEZAS_ESPECIALES(
    NOMBRE VARCHAR(256),
    IMG TEXT
);
