CREATE DATABASE MONARCA;

CREATE TABLE SILLAR(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    PESO INT,
    COLOR VARCHAR(250),
    IMG TEXT
);
CREATE TABLE OVALINES(
    LARGO INT,
    ANCHO INT,
    NOMBRE VARCHAR(250),
    IMG TEXT
)
CREATE TABLE TABIQUE_APARENTE(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    PESO FLOAT
    IMG TEXT,
    NOMBRE VARCHAR(256)
)
CREATE TABLE MURO_LLORON(
    ALTO INT,
    ANCHO INT,
    IMG TEXT,
)
CREATE TABLE FUENTES(
    ALTO INT,
    LARGO INT,
    ANCHO INT,
    IMG TEXT,
    NOMBRE VARCHAR(256)
)
CREATE TABLE ADHESIVOS(
    DESCRIPCION TEXT,
    PESO INT,
    RENDIMIENTO TEXT
)
CREATE TABLE CANTERA(
    LARGO INT,
    ANCHO INT,
    GROSOR INT
)
CREATE TABLE FACHALETA